/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aulapratica01poo1.layout.listar;

import aulapratica01poo1.dados.DadosDisciplina;
import aulapratica01poo1.classes.Disciplina;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eric
 */
public class ListarDisciplinas extends javax.swing.JFrame {

    /**
     * Creates new form ListarDisciplinas
     */
    public ListarDisciplinas() {
        initComponents();
       mostrarDadosTabela(TabelaListarDisciplina);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaListarDisciplina = new javax.swing.JTable();
        Excluir = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();
        Alterar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TabelaListarDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Código", "Carga Horária"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaListarDisciplina);

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Alterar1.setText("Atualizar");
        Alterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alterar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Excluir)
                .addGap(35, 35, 35)
                .addComponent(Alterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Alterar1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Excluir)
                    .addComponent(Alterar)
                    .addComponent(Alterar1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        // TODO add your handling code here:
        if(TabelaListarDisciplina.getSelectedRow() > -1)
        {
            DadosDisciplina.excluir(TabelaListarDisciplina.getSelectedRow());           
            mostrarDadosTabela(TabelaListarDisciplina);
            JOptionPane.showMessageDialog(null, "Excluido com sucesso!");
        }else
            JOptionPane.showMessageDialog(null, "Não existe registro selecionado!");
            
    }//GEN-LAST:event_ExcluirActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        // TODO add your handling code here:
        int index=TabelaListarDisciplina.getSelectedRow();
        if(index>-1)
        {
            int erros=0;
            Color colorError= new Color(255, 77, 77);  
            Disciplina d = DadosDisciplina.getDados().get(index);
            
            
            //variaveis
            int codigo=0;
            String nome=(String)this.TabelaListarDisciplina.getValueAt(TabelaListarDisciplina.getSelectedRow(), 0);
            int carga_horaria=0;
            
            try
            {
                codigo=Integer.parseInt((String)TabelaListarDisciplina.getValueAt(TabelaListarDisciplina.getSelectedRow(), 1));
            }catch(Exception e)
            {
                erros++;
                TabelaListarDisciplina.setBackground(colorError);
            }
            try
            {
                carga_horaria=Integer.parseInt((String)TabelaListarDisciplina.getValueAt(TabelaListarDisciplina.getSelectedRow(), 2));
            }catch(Exception e)
            {
                erros++;
                TabelaListarDisciplina.setBackground(colorError);
            }
            
            
            if(erros==0)
            {
                d.setCarga_horaria(carga_horaria);
                d.setCodigo(codigo);           
                d.setNome(nome);
                mostrarDadosTabela(TabelaListarDisciplina);                
                DadosDisciplina.salvar();
                JOptionPane.showMessageDialog(null, "Dados alterados com sucess.");
            }
            
            
            
            
            
            
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Selecionar uma linha.");
        }
    }//GEN-LAST:event_AlterarActionPerformed

    private void Alterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alterar1ActionPerformed
        // TODO add your handling code here:
        mostrarDadosTabela(TabelaListarDisciplina);
    }//GEN-LAST:event_Alterar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarDisciplinas().setVisible(true);
            }
        });
    }

    public void mostrarDadosTabela(JTable tabela)
    {
      
         String[] colunas = new String[] {"Nome","Codigo","Carga Horaria"};
         String[][] dados = new String[0][0];
         
         DefaultTableModel modelo = new DefaultTableModel(dados,colunas);
         
         tabela.setModel(modelo);
         
         
         for(Disciplina d : DadosDisciplina.getDados())
         {
             
             String codigo;
             String cargahoraria;
             
             
            codigo = Integer.toString(d.getCodigo());
           cargahoraria = Integer.toString(d.getCarga_horaria());
             
             modelo.addRow(new String[] { d.getNome(),codigo,cargahoraria});
             
         }
         
        
       
       
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Alterar1;
    private javax.swing.JButton Excluir;
    private javax.swing.JTable TabelaListarDisciplina;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
