/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aulapratica01poo1.layout.adicionar;

import aulapratica01poo1.classes.CursoPosGraduacao;
import aulapratica01poo1.dados.DadosCursoPosGraduacao;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author vinic
 */
public class AdicionarCursoPosGraduacao extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarCursoPosGraduacao
     */
    public AdicionarCursoPosGraduacao() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        CadastrarCurso = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        codigoCurso = new javax.swing.JTextField();
        nomeCurso = new javax.swing.JTextField();
        duracaoCurso = new javax.swing.JTextField();
        graduacao = new javax.swing.JPanel();
        graduacaoD = new javax.swing.JRadioButton();
        graduacaoM = new javax.swing.JRadioButton();
        graduacaoE = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setText("Cadastrar Novo Curso de Pós Graduação:");

        jLabel8.setText("Codigo:");

        jLabel9.setText("Nome:");

        jLabel10.setText("Duração:");

        jLabel11.setText("Graduação:");

        codigoCurso.setToolTipText("");

        buttonGroup1.add(graduacaoD);
        graduacaoD.setText("Doutorado");
        graduacaoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graduacaoDActionPerformed(evt);
            }
        });

        buttonGroup1.add(graduacaoM);
        graduacaoM.setText("Mestrado");

        buttonGroup1.add(graduacaoE);
        graduacaoE.setText("Especialização");

        javax.swing.GroupLayout graduacaoLayout = new javax.swing.GroupLayout(graduacao);
        graduacao.setLayout(graduacaoLayout);
        graduacaoLayout.setHorizontalGroup(
            graduacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graduacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graduacaoM)
                .addGap(75, 75, 75)
                .addComponent(graduacaoD)
                .addGap(75, 75, 75)
                .addComponent(graduacaoE)
                .addContainerGap())
        );
        graduacaoLayout.setVerticalGroup(
            graduacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graduacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(graduacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(graduacaoM)
                    .addComponent(graduacaoD)
                    .addComponent(graduacaoE))
                .addContainerGap())
        );

        javax.swing.GroupLayout CadastrarCursoLayout = new javax.swing.GroupLayout(CadastrarCurso);
        CadastrarCurso.setLayout(CadastrarCursoLayout);
        CadastrarCursoLayout.setHorizontalGroup(
            CadastrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarCursoLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(CadastrarCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastrarCursoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(66, 66, 66)
                        .addComponent(codigoCurso))
                    .addGroup(CadastrarCursoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(72, 72, 72)
                        .addComponent(nomeCurso))
                    .addGroup(CadastrarCursoLayout.createSequentialGroup()
                        .addGroup(CadastrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(47, 47, 47)
                        .addGroup(CadastrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(duracaoCurso)
                            .addGroup(CadastrarCursoLayout.createSequentialGroup()
                                .addComponent(graduacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        CadastrarCursoLayout.setVerticalGroup(
            CadastrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarCursoLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(codigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(duracaoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(graduacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CadastrarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 236, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(0, 236, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CadastrarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void graduacaoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graduacaoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_graduacaoDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int erros=0;
        Color colorError= new Color(255, 77, 77);  
        tirrarColorError();
        //armazenado dados em variaveis locais
        int codigoCurso=0;
        String nomeCurso=this.nomeCurso.getText();
        int duracao=0;
        String graduacao="";

        //lendo apenas int codigo curso
        try{
            codigoCurso=Integer.parseInt(this.codigoCurso.getText());
        }
        catch(Exception e){
            erros++;
            this.codigoCurso.setBackground(colorError);
        }
        //lendo apenas int duracaoCurso
        try{
            duracao=Integer.parseInt(this.duracaoCurso.getText());

        }catch(Exception e){
            erros++;
            this.duracaoCurso.setBackground(colorError);
        }
        //lendo graduacao
        if(graduacaoM.isSelected())graduacao="M";
        else if(graduacaoD.isSelected())graduacao="D";
        else if(graduacaoE.isSelected())graduacao="E";
        else
        {
            erros++;
            this.graduacao.setBackground(colorError);
        }

        //armazenando dados no cursoGraduacao
        CursoPosGraduacao c =new CursoPosGraduacao();
        //codigo
        if(!c.setCodigo(codigoCurso))
        {
            erros++;
            this.codigoCurso.setBackground(colorError);
        }
        //nome
        if(!c.setNome(nomeCurso))
        {
            erros++;
            this.nomeCurso.setBackground(colorError);
        }
        //duracao
        if(!c.setDuracao(duracao))
        {
            erros++;
            this.duracaoCurso.setBackground(colorError);
        }
        //
        c.setGraduacao(graduacao);
        if(erros==0)
        {
            DadosCursoPosGraduacao.cadastrar(c);
            JOptionPane.showMessageDialog(null, "Curso cadastro realizado com sucesso!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarCursoPosGraduacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarCursoPosGraduacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarCursoPosGraduacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarCursoPosGraduacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarCursoPosGraduacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadastrarCurso;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField codigoCurso;
    private javax.swing.JTextField duracaoCurso;
    private javax.swing.JPanel graduacao;
    private javax.swing.JRadioButton graduacaoD;
    private javax.swing.JRadioButton graduacaoE;
    private javax.swing.JRadioButton graduacaoM;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomeCurso;
    // End of variables declaration//GEN-END:variables

     private void tirrarColorError() {
        
        Color colorJpanelPadrao=new Color(240,240,240);
        
        codigoCurso.setBackground(Color.white);
        nomeCurso.setBackground(Color.white);
        duracaoCurso.setBackground(Color.white);        
        
        graduacao.setBackground(colorJpanelPadrao);
        
    }

}
