/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aulapratica01poo1.layout.adicionar;

import aulapratica01poo1.classes.AlunoGraduacao;
import aulapratica01poo1.classes.AlunoPosGraduacao;
import aulapratica01poo1.classes.Professor;
import aulapratica01poo1.classes.ProjetoPesquisa;
import aulapratica01poo1.dados.DadosAlunoGraduacao;
import aulapratica01poo1.dados.DadosAlunoPosGraduacao;
import aulapratica01poo1.dados.DadosProfessor;
import aulapratica01poo1.dados.DadosProjetoPesquisa;
import aulapratica01poo1.layout.main;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author a11711BSI211
 */
public class AdicionarProjetodePesquisa extends javax.swing.JFrame {

    /**
     * Creates new form ProjetodePesquisa
     */
    public AdicionarProjetodePesquisa() {
        initComponents();
        tirrarColorError();
        listar();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane7 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PanelProjetodePesquisa = new javax.swing.JPanel();
        TituloAdicionarProjetodePesquisa = new javax.swing.JLabel();
        LTitulo = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        LCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LProfessorResponsavel = new javax.swing.JLabel();
        dtFim = new javax.swing.JFormattedTextField();
        dtInicio = new javax.swing.JFormattedTextField();
        codigo = new javax.swing.JFormattedTextField();
        jPanelProf = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProf = new javax.swing.JList<>();
        jPanelEquipe = new javax.swing.JPanel();
        jPanelEquipeAlunoPos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListEquipeAlunoPosGraduacao = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jPanelEquipeProf = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListEquipeProf = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jPanelEquipeAlunoGraduacao = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListEquipeAlunoGraduacao = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        Cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Adicionar Equipe(utilize o shift para selecionar mais de 1):");

        TituloAdicionarProjetodePesquisa.setText("Adicionar Projeto de Pesquisa");

        LTitulo.setText("Título");

        titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloActionPerformed(evt);
            }
        });

        jLabel1.setText("Data de Término");

        LCodigo.setText("Código");

        jLabel3.setText("Data de Início");

        LProfessorResponsavel.setText("Professor Responsável");

        dtFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        dtInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        codigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jListProf.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListProf.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListProf);

        javax.swing.GroupLayout jPanelProfLayout = new javax.swing.GroupLayout(jPanelProf);
        jPanelProf.setLayout(jPanelProfLayout);
        jPanelProfLayout.setHorizontalGroup(
            jPanelProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelProfLayout.setVerticalGroup(
            jPanelProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelProjetodePesquisaLayout = new javax.swing.GroupLayout(PanelProjetodePesquisa);
        PanelProjetodePesquisa.setLayout(PanelProjetodePesquisaLayout);
        PanelProjetodePesquisaLayout.setHorizontalGroup(
            PanelProjetodePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProjetodePesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloAdicionarProjetodePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelProjetodePesquisaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelProjetodePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LTitulo)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LProfessorResponsavel)
                    .addComponent(jPanelProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PanelProjetodePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProjetodePesquisaLayout.createSequentialGroup()
                        .addGroup(PanelProjetodePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LCodigo)
                            .addGroup(PanelProjetodePesquisaLayout.createSequentialGroup()
                                .addGroup(PanelProjetodePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dtFim, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(PanelProjetodePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelProjetodePesquisaLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel3))
                                    .addGroup(PanelProjetodePesquisaLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(dtInicio)))))
                        .addGap(14, 14, 14))
                    .addGroup(PanelProjetodePesquisaLayout.createSequentialGroup()
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelProjetodePesquisaLayout.setVerticalGroup(
            PanelProjetodePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProjetodePesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloAdicionarProjetodePesquisa)
                .addGap(29, 29, 29)
                .addGroup(PanelProjetodePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LCodigo))
                .addGap(27, 27, 27)
                .addGroup(PanelProjetodePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(PanelProjetodePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LProfessorResponsavel)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(PanelProjetodePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProjetodePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dtFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(PanelProjetodePesquisa);

        jListEquipeAlunoPosGraduacao.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListEquipeAlunoPosGraduacao);

        jLabel5.setText("Selecione os alunos Pós Graduacao(utilize o shift e ctrl para selecionar mais de 1):");

        javax.swing.GroupLayout jPanelEquipeAlunoPosLayout = new javax.swing.GroupLayout(jPanelEquipeAlunoPos);
        jPanelEquipeAlunoPos.setLayout(jPanelEquipeAlunoPosLayout);
        jPanelEquipeAlunoPosLayout.setHorizontalGroup(
            jPanelEquipeAlunoPosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEquipeAlunoPosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEquipeAlunoPosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );
        jPanelEquipeAlunoPosLayout.setVerticalGroup(
            jPanelEquipeAlunoPosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEquipeAlunoPosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jListEquipeProf.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListEquipeProf);

        jLabel4.setText("Selecione os Professores((utilize o shift e ctrl para selecionar mais de 1):");

        javax.swing.GroupLayout jPanelEquipeProfLayout = new javax.swing.GroupLayout(jPanelEquipeProf);
        jPanelEquipeProf.setLayout(jPanelEquipeProfLayout);
        jPanelEquipeProfLayout.setHorizontalGroup(
            jPanelEquipeProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEquipeProfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEquipeProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        jPanelEquipeProfLayout.setVerticalGroup(
            jPanelEquipeProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEquipeProfLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jListEquipeAlunoGraduacao.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jListEquipeAlunoGraduacao);

        jLabel6.setText("Selecione os alunos Graduação(utilize o shift e ctrl para selecionar mais de 1):");

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEquipeAlunoGraduacaoLayout = new javax.swing.GroupLayout(jPanelEquipeAlunoGraduacao);
        jPanelEquipeAlunoGraduacao.setLayout(jPanelEquipeAlunoGraduacaoLayout);
        jPanelEquipeAlunoGraduacaoLayout.setHorizontalGroup(
            jPanelEquipeAlunoGraduacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEquipeAlunoGraduacaoLayout.createSequentialGroup()
                .addGroup(jPanelEquipeAlunoGraduacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEquipeAlunoGraduacaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelEquipeAlunoGraduacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanelEquipeAlunoGraduacaoLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(Cadastrar)))
                .addContainerGap())
        );
        jPanelEquipeAlunoGraduacaoLayout.setVerticalGroup(
            jPanelEquipeAlunoGraduacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEquipeAlunoGraduacaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(Cadastrar))
        );

        javax.swing.GroupLayout jPanelEquipeLayout = new javax.swing.GroupLayout(jPanelEquipe);
        jPanelEquipe.setLayout(jPanelEquipeLayout);
        jPanelEquipeLayout.setHorizontalGroup(
            jPanelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEquipeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEquipeAlunoPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelEquipeProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelEquipeAlunoGraduacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelEquipeLayout.setVerticalGroup(
            jPanelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEquipeLayout.createSequentialGroup()
                .addComponent(jPanelEquipeProf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEquipeAlunoPos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEquipeAlunoGraduacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jScrollPane6.setViewportView(jPanel1);

        jScrollPane7.setViewportView(jScrollPane6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // TODO add your handling code here:

        int erros=0;

        tirrarColorError();

        String codigo = this.codigo.getText();
        String titulo = this.titulo.getText();
        String data_de_inico=this.dtInicio.getText();
        String data_de_fim=this.dtFim.getText();
        Professor p=null;

        //getProfessor
        int index = this.jListProf.getSelectedIndex();
        if(index>-1){p=DadosProfessor.getDados().get(index);}
        else{erros++;this.jPanelProf.setBackground(main.colorError);}

        //sets
        ProjetoPesquisa pp = new ProjetoPesquisa();
        if(!pp.setCodigo(codigo)){erros++;this.codigo.setBackground(main.colorError);}
        if(!pp.setTitulo(titulo)){erros++;this.titulo.setBackground(main.colorError);}
        if(!pp.setDtFim(data_de_fim)){erros++;this.dtFim.setBackground(main.colorError);}
        if(!pp.setDtInicio(data_de_inico)){erros++;this.dtInicio.setBackground(main.colorError);}
            
        //equipe
        int equipe=0;
        int selected[]=this.jListEquipeProf.getSelectedIndices();
        equipe+=selected.length;
        for(int i=0;i<selected.length;i++)
        {
            pp.adicionar(DadosProfessor.getDados().get(selected[i]));
        }

        selected=this.jListEquipeAlunoGraduacao.getSelectedIndices();
        equipe+=selected.length;
        for(int i=0;i<selected.length;i++)
        {
            pp.adicionar(DadosAlunoGraduacao.getDados().get(selected[i]));
        }
        selected=this.jListEquipeAlunoPosGraduacao.getSelectedIndices();
        equipe+=selected.length;
        for(int i=0;i<selected.length;i++)
        {
            pp.adicionar(DadosAlunoPosGraduacao.getDados().get(selected[i]));
        }
        if(equipe==0)
        {
            erros++;
            this.jPanelEquipe.setBackground(main.colorError);
        }

        if(erros==0)
        {
            pp.setProfessorResponsavel(p);
            DadosProjetoPesquisa.cadastrar(pp);
            JOptionPane.showMessageDialog(null, "Projeto Pesquisa Cadastrado");
        }

    }//GEN-LAST:event_CadastrarActionPerformed

    private void tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarProjetodePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarProjetodePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarProjetodePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarProjetodePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarProjetodePesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JLabel LCodigo;
    private javax.swing.JLabel LProfessorResponsavel;
    private javax.swing.JLabel LTitulo;
    private javax.swing.JPanel PanelProjetodePesquisa;
    private javax.swing.JLabel TituloAdicionarProjetodePesquisa;
    private javax.swing.JFormattedTextField codigo;
    private javax.swing.JFormattedTextField dtFim;
    private javax.swing.JFormattedTextField dtInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jListEquipeAlunoGraduacao;
    private javax.swing.JList<String> jListEquipeAlunoPosGraduacao;
    private javax.swing.JList<String> jListEquipeProf;
    private javax.swing.JList<String> jListProf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelEquipe;
    private javax.swing.JPanel jPanelEquipeAlunoGraduacao;
    private javax.swing.JPanel jPanelEquipeAlunoPos;
    private javax.swing.JPanel jPanelEquipeProf;
    private javax.swing.JPanel jPanelProf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables

      private void tirrarColorError() {
          this.codigo.setBackground(Color.WHITE);
          this.dtFim.setBackground(Color.WHITE);
          this.dtInicio.setBackground(Color.WHITE);
          this.titulo.setBackground(Color.WHITE);
          this.jPanelProf.setBackground(Color.WHITE);
      }
      private void listar()
      {
          DefaultListModel modelo = new DefaultListModel();
          
          jListProf.setModel(modelo);
          
          for(Professor p : DadosProfessor.getDados())
          {
              modelo.addElement(p.getNome());
          }
          //-----//
          modelo = new DefaultListModel();
          jListEquipeProf.setModel(modelo);
          
          for(Professor p : DadosProfessor.getDados())
          {
              modelo.addElement(p.getNome());
          }
          //-----//
          modelo = new DefaultListModel();
          jListEquipeAlunoGraduacao.setModel(modelo);
          
          for(AlunoGraduacao p : DadosAlunoGraduacao.getDados())
          {
              modelo.addElement(p.getNome());
          }
          //-----//
          modelo = new DefaultListModel();
          jListEquipeAlunoPosGraduacao.setModel(modelo);
          
          for(AlunoPosGraduacao p : DadosAlunoPosGraduacao.getDados())
          {
              modelo.addElement(p.getNome());
          }
      }
}
